# Generated by Django 3.1.3 on 2020-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTU', '0003_event1'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='userName',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
