# Generated by Django 3.1.3 on 2020-11-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTU', '0004_studentinfo_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='event1',
            new_name='eventbell',
        ),
    ]
