# Generated by Django 3.1.3 on 2020-11-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTU', '0005_auto_20201129_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventkpmg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='eventwelcome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('contactno', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
