# Generated by Django 3.1.3 on 2020-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTU', '0006_eventkpmg_eventwelcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=200)),
                ('EmailAddress', models.CharField(max_length=200)),
                ('Message', models.CharField(max_length=200)),
            ],
        ),
    ]
