# Generated by Django 3.1.3 on 2020-11-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTU', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='EmailAddress',
            new_name='Emailaddress',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='FullName',
            new_name='Fullname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='PhoneNumber',
            new_name='Phonenumber',
        ),
    ]
