# Generated by Django 3.1.3 on 2020-12-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTU', '0008_auto_20201130_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialServices',
        ),
    ]
