# Generated by Django 3.1.2 on 2020-12-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTU', '0009_delete_financialservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='confirm',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
